deployment:
  replicaset: 4
  #pulling from harbor:
  #imagename: 192.168.1.179:80/devops/myapp
  #imagetag: v1
  pullPolicy: IfNotPresent
  #pulling from dockerhub: 
  imagename: philiprime97/aws-web
  imagetag: ${BUILD_NUMBER}

service:
  type: NodePort
  port: 5001
  targetport: 5001
  nodePort: 31001

ingress:
  enabled: true
  ingressClassName: nginx
  host: awsviewer.com   

aws:
  accessKeyId: ""
  secretAccessKey: ""
  region: "eu-north-1"

podMonitor:
  port: http
  path: /metrics
  interval: 30s
  release: prometheus 
